import type { ToolDefinition } from "@/features/tools/types";

const CATALOG_UPDATED_AT = "2026-08-14T00:00:00.000Z";

export const defaultToolCatalog: ToolDefinition[] = [
  {
    id: "server.basic_info",
    implementation: "serverBasicInfo",
    name: "服务器基本信息获取工具",
    description: "获取服务器操作系统、内核、CPU、核心数、内存、磁盘、运行时间和已部署软件环境。",
    usageInstructions: "需要确认服务器环境或规划部署方案时使用。只依据返回结果判断环境，不得猜测未返回的软件或配置。",
    inputSchema: { type: "object", additionalProperties: false, properties: {}, required: [] },
    outputDescription: "返回服务器硬件、操作系统和软件环境的结构化快照。",
    planMode: "regular",
    completionMode: "continue",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "server.realtime_metrics",
    implementation: "serverRealtimeMetrics",
    name: "服务器实时数据获取工具",
    description: "获取服务器当前 CPU、内存、磁盘和网络吞吐数据。",
    usageInstructions: "需要判断当前资源负载时使用。采样只代表采集时刻，不应据此推断长期趋势。",
    inputSchema: { type: "object", additionalProperties: false, properties: {}, required: [] },
    outputDescription: "返回带采样时间的 CPU、内存、磁盘和网络指标。",
    planMode: "regular",
    completionMode: "continue",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "server.resolve_connection",
    implementation: "serverResolveConnection",
    name: "服务器连接资料查询工具",
    description: "按目标地址查询服务器管理记录、SSH 用户名以及系统钥匙串中是否存在密码。",
    usageInstructions: "输入目标 host 和 port。工具只返回用户名、凭据是否可用及不可逆 credentialRef，不返回密码明文。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        host: { type: "string", description: "目标服务器 IP 地址或域名。" },
        port: { type: "integer", minimum: 1, maximum: 65535, default: 22 },
      },
      required: ["host"],
    },
    outputDescription: "返回目标服务器是否已纳管、用户名、端口、凭据可用状态和 credentialRef。",
    planMode: "standalone",
    completionMode: "refine",
    refinementScope: "active-skill",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "server.connect",
    implementation: "serverConnect",
    name: "SSH 服务器连接工具",
    description: "在当前可见终端的真实 PTY 中执行 SSH 登录，并让后续命令继续运行在目标服务器。",
    usageInstructions: "输入目标地址，并使用 credentialRef 或 username + passwordSecretKey 引用凭据。工具只负责在当前终端完成一次 SSH 登录，不负责网络预检或登录后的业务验收。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        host: { type: "string", description: "目标服务器 IP 地址或域名。" },
        port: { type: "integer", minimum: 1, maximum: 65535, default: 22, description: "SSH 服务端口。" },
        username: { type: "string", description: "SSH 登录用户名。" },
        passwordSecretKey: { type: "string", description: "已由用户输入工具安全收集的密码参数 key，不是密码值。" },
        credentialRef: { type: "string", description: "服务器连接资料查询工具返回的不可逆凭据引用。" },
        name: { type: "string", description: "服务器在 Opsark 中的显示名称。" },
        group: { type: "string", description: "可选的服务器分组。" },
      },
      required: ["host"],
    },
    outputDescription: "返回终端内 SSH 跳转状态、目标地址和用户名，不返回密码。",
    planMode: "standalone",
    completionMode: "refine",
    refinementScope: "active-skill",
    executionMode: "terminal",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "secret.metadata",
    implementation: "secretMetadata",
    name: "服务器信息数据管理工具",
    description: "管理数据库账号、访问令牌等敏感变量的名称、用途和作用域。模型不能读取真实值。",
    usageInstructions: "只使用语义匹配的变量。变量不存在或用途不明确时，应请求用户提供新的明确变量。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        key: { type: "string" },
        description: { type: "string" },
        scope: { type: "string", enum: ["global", "server"] },
      },
      required: ["key", "description", "scope"],
    },
    outputDescription: "返回敏感变量元数据和占位符，不返回真实值。",
    planMode: "regular",
    completionMode: "continue",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "secret.merge_command",
    implementation: "secretMergeCommand",
    name: "指令合并工具",
    description: "在执行阶段将命令中的敏感变量占位符合并为真实值，并保证展示和日志继续脱敏。",
    usageInstructions: "命令必须使用 ${secret.KEY} 占位符。不得索取、输出或推断真实敏感值。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { command: { type: "string" } },
      required: ["command"],
    },
    outputDescription: "返回仅供执行器使用的合并结果；模型和日志只接收脱敏命令。",
    planMode: "regular",
    completionMode: "continue",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "user.request_input",
    implementation: "userRequestInput",
    name: "用户输入工具",
    description: "以结构化表单请求用户补充任务必需信息，每个参数均显示名称、用途、必填状态和输入提示。",
    usageInstructions: "仅在完成任务确实缺少用户信息时调用。必须作为当前计划唯一的信息收集步骤，提交后再生成后续计划。每个字段必须提供 label 和 description，明确告知“参数是什么”和“为什么需要”；敏感值必须使用 password 类型。不得请求已能从系统工具获得或与任务无关的信息。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        title: { type: "string", description: "表单标题，说明需要用户补充什么信息。" },
        description: { type: "string", description: "表单整体说明，告知这些信息将用于什么操作。" },
        fields: {
          type: "array",
          minItems: 1,
          maxItems: 8,
          description: "用户需要填写的参数列表。",
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              key: { type: "string", description: "程序使用的参数名。" },
              label: { type: "string", description: "展示给用户的参数名称。" },
              description: { type: "string", description: "说明参数是什么、将用于什么操作。" },
              type: { type: "string", enum: ["text", "password", "number"] },
              placeholder: { type: "string", description: "不包含真实敏感值的输入示例。" },
              required: { type: "boolean", description: "该参数是否必填。" },
            },
            required: ["key", "label", "description", "type", "required"],
          },
        },
      },
      required: ["title", "fields"],
    },
    outputDescription: "返回用户确认的字段值；敏感字段不会写入模型上下文或普通日志。",
    planMode: "standalone",
    completionMode: "refine",
    refinementScope: "always",
    executionMode: "user-input",
    enabled: true,
    builtIn: true,
    version: 2,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "files.get_structure",
    implementation: "getRemoteFileStructure",
    name: "文件数据结构获取工具",
    description: "只读获取远端指定目录的文件和目录树。",
    usageInstructions: "输入绝对路径和当前场景需要排除的目录；工具本身不预设技术栈。结果截断时可缩小范围再次获取。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        rootPath: { type: "string", description: "远端绝对目录路径" },
        excludeDirectories: { type: "array", items: { type: "string" } },
        maxDepth: { type: "integer", minimum: 1, maximum: 20, default: 6 },
        maxNodes: { type: "integer", minimum: 1, maximum: 10000, default: 2000 },
        includeHidden: { type: "boolean", default: false },
      },
      required: ["rootPath"],
    },
    outputDescription: "返回稳定排序的目录树、节点总数、实际排除项、截断标记和读取警告，不返回文件内容。",
    planMode: "standalone",
    completionMode: "refine",
    refinementScope: "active-skill",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "files.transfer_between_servers",
    implementation: "transferFileBetweenServers",
    name: "服务器间文件传输工具",
    description: "使用 Opsark 已保存的两台服务器凭据，在桌面后端中流式中转文件并进行 SHA-256 校验。",
    usageInstructions: "输入源文件、目标服务器和目标路径。工具使用受管凭据流式中转并校验，不要求源服务器持有目标凭据。是否选用该工具由当前 Skill 决定。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        sourcePath: { type: "string", description: "当前服务器上的源文件绝对路径" },
        targetServer: { type: "string", description: "目标服务器 ID、名称或地址" },
        targetPath: { type: "string", description: "目标文件绝对路径，必须包含文件名" },
        overwrite: { type: "boolean", default: false },
      },
      required: ["sourcePath", "targetServer", "targetPath"],
    },
    outputDescription: "返回源路径、目标路径、字节数、目标服务器 ID 和 SHA-256 校验值。",
    planMode: "regular",
    completionMode: "continue",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
];
