import type { ToolDefinition } from "@/features/tools/types";

const CATALOG_UPDATED_AT = "2026-08-14T00:00:00.000Z";

export const defaultToolCatalog: ToolDefinition[] = [
  {
    id: "server.basic_info",
    implementation: "serverBasicInfo",
    name: "服务器基本信息获取工具",
    description: "获取服务器操作系统、内核、CPU、核心数、内存、磁盘、运行时间和已部署软件环境。",
    usageInstructions: "需要确认服务器环境或规划部署方案时使用。只依据返回结果判断环境，不得猜测未返回的软件或配置。",
    inputSchema: { type: "object", additionalProperties: false, properties: {}, required: [] },
    outputDescription: "返回服务器硬件、操作系统和软件环境的结构化快照。",
    planMode: "regular",
    completionMode: "continue",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "server.realtime_metrics",
    implementation: "serverRealtimeMetrics",
    name: "服务器实时数据获取工具",
    description: "获取服务器当前 CPU、内存、磁盘和网络吞吐数据。",
    usageInstructions: "需要判断当前资源负载时使用。采样只代表采集时刻，不应据此推断长期趋势。",
    inputSchema: { type: "object", additionalProperties: false, properties: {}, required: [] },
    outputDescription: "返回带采样时间的 CPU、内存、磁盘和网络指标。",
    planMode: "regular",
    completionMode: "continue",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "server.resolve_connection",
    implementation: "serverResolveConnection",
    name: "服务器连接资料查询工具",
    description: "按目标地址查询服务器管理记录或当前服务器长期保存的 SSH 凭据组。",
    usageInstructions: "输入目标 host 和 port。工具优先返回已纳管服务器引用，否则可返回唯一匹配的 server-credential 引用；不返回凭据组中的用户名或密码真实值。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        host: { type: "string", description: "目标服务器 IP 地址或域名。" },
        port: { type: "integer", minimum: 1, maximum: 65535, default: 22 },
      },
      required: ["host"],
    },
    outputDescription: "返回目标是否有可用连接资料、端口和 credentialRef；只有已纳管服务器可返回公开用户名，服务器凭据组不返回真实值。",
    planMode: "standalone",
    completionMode: "refine",
    refinementScope: "active-skill",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 2,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "server.connect",
    implementation: "serverConnect",
    name: "SSH 服务器连接工具",
    description: "在当前可见终端的真实 PTY 中执行 SSH 登录，并让后续命令继续运行在目标服务器。",
    usageInstructions: "输入需要登录的目标地址，并优先使用 server.resolve_connection 或 serverCredentialGroups 给出的 credentialRef；仅兼容旧流程时使用 username + passwordSecretKey。缺少匹配凭据时必须先调用 user.request_input 同表单收集用户名和密码。工具会改变当前终端所在服务器，只用于用户要求的终端 SSH 登录，不是 scp 或服务器间文件传输的凭据准备/中转步骤。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        host: { type: "string", description: "目标服务器 IP 地址或域名。" },
        port: { type: "integer", minimum: 1, maximum: 65535, default: 22, description: "SSH 服务端口。" },
        username: { type: "string", description: "SSH 登录用户名。" },
        passwordSecretKey: { type: "string", description: "已由用户输入工具安全收集的密码参数 key，不是密码值。" },
        credentialRef: { type: "string", description: "服务器连接资料查询工具返回的不可逆凭据引用。" },
        name: { type: "string", description: "服务器在 Opsark 中的显示名称。" },
        group: { type: "string", description: "可选的服务器分组。" },
      },
      required: ["host"],
    },
    outputDescription: "返回终端内 SSH 跳转状态、目标地址和用户名占位元数据，不返回凭据组的真实值。",
    planMode: "standalone",
    completionMode: "refine",
    refinementScope: "active-skill",
    executionMode: "terminal",
    enabled: true,
    builtIn: true,
    version: 2,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "secret.metadata",
    implementation: "secretMetadata",
    name: "服务器信息数据管理工具",
    description: "管理当前服务器长期保存的数据库账号、Git 用户名/令牌和其他敏感变量及凭据组。模型不能读取真实值。",
    usageInstructions: "任何当前服务器的任务都应直接复用用途和目标匹配的已保存变量或 serverCredentialGroups，不得重复询问。只在值缺失、用途冲突或多组无法唯一选择时请求用户。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        key: { type: "string" },
        description: { type: "string" },
        scope: { type: "string", enum: ["global", "server"] },
      },
      required: ["key", "description", "scope"],
    },
    outputDescription: "返回敏感变量元数据和占位符，不返回真实值。",
    planMode: "regular",
    completionMode: "continue",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "secret.merge_command",
    implementation: "secretMergeCommand",
    name: "指令合并工具",
    description: "在执行阶段将命令中的敏感变量占位符合并为真实值，并保证展示和日志继续脱敏。",
    usageInstructions: "命令必须使用 ${secret.KEY} 占位符。不得索取、输出或推断真实敏感值。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { command: { type: "string" } },
      required: ["command"],
    },
    outputDescription: "返回仅供执行器使用的合并结果；模型和日志只接收脱敏命令。",
    planMode: "regular",
    completionMode: "continue",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "user.request_input",
    implementation: "userRequestInput",
    name: "用户输入工具",
    description: "以结构化表单请求用户补充任务必需信息，每个参数均显示名称、用途、必填状态和输入提示。",
    usageInstructions: "仅在完成任务确实缺少用户信息时调用。必须作为当前计划唯一的信息收集步骤，提交后再生成后续计划。每个字段必须提供 label 和 description；敏感值必须使用 password 类型。收集用户名+密码/令牌时，两个字段必须各自提供 credential 对象，使用相同 group/kind/target 和不同 role，不得依赖 label/description 自然语言推断配对。完整凭据组会按服务器长期保存，后续任务应复用 serverCredentialGroups，不得重复索取。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        title: { type: "string", description: "表单标题，说明需要用户补充什么信息。" },
        description: { type: "string", description: "表单整体说明，告知这些信息将用于什么操作。" },
        fields: {
          type: "array",
          minItems: 1,
          maxItems: 8,
          description: "用户需要填写的参数列表。",
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              key: { type: "string", description: "程序使用的参数名。" },
              label: { type: "string", description: "展示给用户的参数名称。" },
              description: { type: "string", description: "说明参数是什么、将用于什么操作。" },
              type: { type: "string", enum: ["text", "password", "number"] },
              placeholder: { type: "string", description: "不包含真实敏感值的输入示例。" },
              required: { type: "boolean", description: "该参数是否必填。" },
              credential: {
                type: "object",
                additionalProperties: false,
                description: "用户名/密码或令牌的显式凭据组契约。",
                properties: {
                  group: { type: "string", description: "同一表单内两个凭据字段共用的组标识。" },
                  kind: { type: "string", enum: ["git-https", "ssh-password", "database", "service"] },
                  role: { type: "string", enum: ["username", "secret"] },
                  target: { type: "string", description: "认证目标主机或服务标识，不包含凭据。" },
                },
                required: ["group", "kind", "role", "target"],
              },
            },
            required: ["key", "label", "description", "type", "required"],
          },
        },
      },
      required: ["title", "fields"],
    },
    outputDescription: "返回非敏感字段值与敏感字段占位符；凭据真实值不会写入模型上下文或普通日志。",
    planMode: "standalone",
    completionMode: "refine",
    refinementScope: "always",
    executionMode: "user-input",
    enabled: true,
    builtIn: true,
    version: 3,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "files.get_structure",
    implementation: "getRemoteFileStructure",
    name: "文件数据结构获取工具",
    description: "只读获取远端指定目录的紧凑文本目录树。",
    usageInstructions: "固定格式为 opsark-tool files.get_structure {...}，工具 ID 前不得添加 --。输入绝对路径即可；默认排除版本库、依赖缓存和构建产物，默认最多 4 层、600 个节点。结果截断时应缩小 rootPath 再获取，不要盲目提高上限。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        rootPath: { type: "string", description: "远端绝对目录路径" },
        excludeDirectories: { type: "array", items: { type: "string" } },
        maxDepth: { type: "integer", minimum: 1, maximum: 20, default: 4 },
        maxNodes: { type: "integer", minimum: 1, maximum: 10000, default: 600 },
        includeHidden: { type: "boolean", default: false },
      },
      required: ["rootPath"],
    },
    outputDescription: "模型仅接收一个稳定排序的 tree 文本字段；截断状态由执行器单独记录，不返回节点对象、文件内容或重复元数据。",
    planMode: "standalone",
    completionMode: "refine",
    refinementScope: "active-skill",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 2,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "files.read_content",
    implementation: "readRemoteFileContent",
    name: "文件内容读取工具",
    description: "有界、只读地读取远端 UTF-8 文本文件，为项目文档、声明文件和配置分析提供真实证据。",
    usageInstructions: "仅在已确认的绝对文件路径上使用。默认最多读取 64 KiB，最大 256 KiB；二进制文件会拒绝读取，敏感值在进入模型上下文前脱敏。目录结构不足以证明技术栈时，应使用本工具读取 README、依赖声明、锁文件或示例配置。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        path: { type: "string", description: "需要读取的远端文件绝对路径。" },
        maxBytes: { type: "integer", minimum: 1, maximum: 262144, default: 65536 },
      },
      required: ["path"],
    },
    outputDescription: "返回脱敏后的 UTF-8 文本、文件总字节数、返回字节数和截断状态。",
    planMode: "standalone",
    completionMode: "refine",
    refinementScope: "active-skill",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "software.check",
    implementation: "checkSoftware",
    name: "软件可用性检查工具",
    description: "在当前任务绑定终端中检查指定软件是否存在，并获取真实可执行路径和版本首行。",
    usageInstructions: "一次检查 1 到 20 个由项目证据或用户需求明确指出的软件；不得借此扫描整台服务器或猜测技术栈。该工具只检查，不安装、不升级、不启动服务。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        names: { type: "array", minItems: 1, maxItems: 20, items: { type: "string" }, description: "要检查的精确命令名。" },
        includeVersions: { type: "boolean", default: true },
      },
      required: ["names"],
    },
    outputDescription: "返回每个软件的安装状态、命令路径和版本首行。",
    planMode: "standalone",
    completionMode: "refine",
    refinementScope: "active-skill",
    executionMode: "terminal",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "files.transfer_between_servers",
    implementation: "transferFileBetweenServers",
    name: "服务器间文件传输工具",
    description: "使用 Opsark 已保存的两台服务器凭据，在桌面后端中流式中转文件并进行 SHA-256 校验。",
    usageInstructions: "输入源文件、目标服务器和目标路径。工具使用受管凭据流式中转并校验，不要求源服务器持有目标凭据。是否选用该工具由当前 Skill 决定。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        sourcePath: { type: "string", description: "当前服务器上的源文件绝对路径" },
        targetServer: { type: "string", description: "目标服务器 ID、名称或地址" },
        targetPath: { type: "string", description: "目标文件绝对路径，必须包含文件名" },
        overwrite: { type: "boolean", default: false },
      },
      required: ["sourcePath", "targetServer", "targetPath"],
    },
    outputDescription: "返回源路径、目标路径、字节数、目标服务器 ID 和 SHA-256 校验值。",
    planMode: "regular",
    completionMode: "continue",
    executionMode: "local",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
];
