import type { ToolDefinition } from "@/features/tools/types";

const CATALOG_UPDATED_AT = "2026-08-14T00:00:00.000Z";

export const defaultToolCatalog: ToolDefinition[] = [
  {
    id: "server.basic_info",
    implementation: "serverBasicInfo",
    name: "服务器基本信息获取工具",
    description: "获取服务器操作系统、内核、CPU、核心数、内存、磁盘、运行时间和已部署软件环境。",
    usageInstructions: "需要确认服务器环境或规划部署方案时使用。只依据返回结果判断环境，不得猜测未返回的软件或配置。",
    inputSchema: { type: "object", additionalProperties: false, properties: {}, required: [] },
    outputDescription: "返回服务器硬件、操作系统和软件环境的结构化快照。",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "server.realtime_metrics",
    implementation: "serverRealtimeMetrics",
    name: "服务器实时数据获取工具",
    description: "获取服务器当前 CPU、内存、磁盘和网络吞吐数据。",
    usageInstructions: "需要判断当前资源负载时使用。采样只代表采集时刻，不应据此推断长期趋势。",
    inputSchema: { type: "object", additionalProperties: false, properties: {}, required: [] },
    outputDescription: "返回带采样时间的 CPU、内存、磁盘和网络指标。",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "secret.metadata",
    implementation: "secretMetadata",
    name: "服务器信息数据管理工具",
    description: "管理数据库账号、访问令牌等敏感变量的名称、用途和作用域。模型不能读取真实值。",
    usageInstructions: "只使用语义匹配的变量。变量不存在或用途不明确时，应请求用户提供新的明确变量。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        key: { type: "string" },
        description: { type: "string" },
        scope: { type: "string", enum: ["global", "server"] },
      },
      required: ["key", "description", "scope"],
    },
    outputDescription: "返回敏感变量元数据和占位符，不返回真实值。",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "secret.merge_command",
    implementation: "secretMergeCommand",
    name: "指令合并工具",
    description: "在执行阶段将命令中的敏感变量占位符合并为真实值，并保证展示和日志继续脱敏。",
    usageInstructions: "命令必须使用 ${secret.KEY} 占位符。不得索取、输出或推断真实敏感值。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { command: { type: "string" } },
      required: ["command"],
    },
    outputDescription: "返回仅供执行器使用的合并结果；模型和日志只接收脱敏命令。",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "user.request_input",
    implementation: "userRequestInput",
    name: "用户输入工具",
    description: "根据结构化字段定义请求用户输入缺失的信息，密码类字段默认不回显。",
    usageInstructions: "仅在完成任务确实缺少用户信息时调用，并清楚说明字段用途。不得请求无关信息。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        title: { type: "string" },
        fields: { type: "array", items: { type: "object" } },
      },
      required: ["title", "fields"],
    },
    outputDescription: "返回用户确认的字段值；敏感字段不会写入模型上下文或普通日志。",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
  {
    id: "files.get_structure",
    implementation: "getRemoteFileStructure",
    name: "文件数据结构获取工具",
    description: "只读获取远端指定目录的文件和目录树，用于在部署、排障或代码分析前了解真实项目结构。",
    usageInstructions: "未知项目应先查看结构再决定后续步骤。计划步骤的 command 使用：opsark-tool files.get_structure {\"rootPath\":\"/绝对路径\",\"excludeDirectories\":[]}，validation 使用 true。不得根据文件名猜测内容；结果截断时应缩小范围继续获取。",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        rootPath: { type: "string", description: "远端绝对目录路径" },
        excludeDirectories: { type: "array", items: { type: "string" } },
        maxDepth: { type: "integer", minimum: 1, maximum: 20, default: 6 },
        maxNodes: { type: "integer", minimum: 1, maximum: 10000, default: 2000 },
        includeHidden: { type: "boolean", default: false },
      },
      required: ["rootPath"],
    },
    outputDescription: "返回稳定排序的目录树、节点总数、实际排除项、截断标记和读取警告，不返回文件内容。",
    enabled: true,
    builtIn: true,
    version: 1,
    updatedAt: CATALOG_UPDATED_AT,
  },
];
