import { describe, expect, it, vi } from "vitest";
import type { OpsTask, PlanStep } from "@/types";
import { taskAttemptContext } from "./attemptState";
import { assertTaskPlanAuthorization, hasVerifiedRecovery, isRelatedRecoveryStep, recoveryPlanningContext, persistedRecoveryContract, validateRecoveryReferences } from "./recoveryContract";
import { remainingPlanCanRepairPostcondition, remainingPlanCanRecoverExecutionFailure } from "./evidenceReview";
import { findUnresolvedBlockingStep, resolveTaskProgression, selectAdjustmentSteps, selectContinuationSteps } from "./taskProgression";
import { reviewPrecondition } from "./reviewService";
import { applyExecutionEvidenceReview } from "./reviewCoordination";
import { normalizePlanPreconditions } from "./planNormalizer";
import { runEvidenceReviewPipeline } from "./stepReviewPipeline";

function fixture() {
  const task: OpsTask = { id: "task", serverId: "server", title: "Build project A", status: "running",
    permission: "managed", modelId: "model", messages: [], plan: [], currentRoundId: "round",
    createdAt: "now", updatedAt: "now" };
  const context = taskAttemptContext(task);
  const failed: PlanStep = { id: "failed-a", kind: "change", title: "Build project A", description: "Build",
    command: "cd /opt/a && npm run build", validation: "test -d /opt/a/dist >/dev/null", expected: "artifact",
    risk: "low", status: "failed", attemptContext: context,
    result: { executionStatus: "failed", observationStatus: "unknown", exitCode: 1,
      facts: {}, warnings: [], evidenceIds: [] } };
  const repair: PlanStep = { ...failed, id: "repair-a", command: "cd /opt/a && npm install dependency",
    status: "pending", result: undefined, attemptContext: undefined,
    recovery: { failedStepId: failed.id, targetContext: context, purpose: "repair" } };
  const verify: PlanStep = { ...repair, id: "verify-a", kind: "observe", command: failed.validation,
    validation: "", recovery: { ...repair.recovery!, purpose: "verify" } };
  const next: PlanStep = { ...repair, id: "business", command: "systemctl restart app", recovery: undefined };
  task.plan = [failed, repair, verify, next];
  return { task, failed, repair, verify, next, context };
}

function finish(step: PlanStep, context: string) {
  step.status = "completed";
  step.attemptContext = context;
  step.result = { executionStatus: "success", observationStatus: "matched", exitCode: 0,
    facts: {}, warnings: [], evidenceIds: [step.id] };
  step.evidence = [{ id: step.id, type: "command", source: "main", facts: {}, rawOutput: "ok", collectedAt: "now" }];
}

describe("optional recovery audit references and preserved execution facts", () => {
  it("allows the incident's revised build verification without rewriting the original failed attempt", async () => {
    const { task, failed, verify, context } = fixture();
    failed.command = "cd /opt/report && bash build.sh --legacy-peer-deps";
    failed.validation = "test -f /opt/report/build/aj-report-*.zip && echo built";
    failed.expected = "build package exists";
    failed.output = "npm ERR! code ERESOLVE";
    const originalFailure = JSON.parse(JSON.stringify(failed));
    const revised: PlanStep = { ...verify, id: "verify-new-build", command: "test -s /opt/report/build/aj-report-current.zip",
      expected: "The artifact generated by this build is nonempty" };
    task.plan = [failed, revised];

    expect(() => validateRecoveryReferences([failed], [revised], context)).not.toThrow();
    expect((await reviewPrecondition({ task, step: revised, blockerStep: failed })).allowed).toBe(true);
    finish(revised, context);
    // The new method goes to goal review. It is not forged into a successful
    // execution of the old method merely because the new command exited zero.
    expect(hasVerifiedRecovery(failed, revised)).toBe(false);
    expect(resolveTaskProgression(task).kind).toBe("complete");
    expect(failed).toEqual(originalFailure);
    const planning = recoveryPlanningContext(task);
    expect(planning.failedAttempts[0].verification).toMatchObject({ usage: "historical_reference", allowsRevisedVerification: true });
    expect(planning.instruction).toContain("可修正原验收命令和 expected");
    expect(planning.instruction).toContain("被新方案替代的旧路径无需逐条执行成功");
  });

  it("permits read-only diagnosis with no recovery metadata after a failed build", async () => {
    const { task, failed, verify, context } = fixture();
    const diagnosis: PlanStep = { ...verify, id: "inspect-build-script", command: "sed -n '1,160p' /opt/report/build.sh",
      expected: "Read the npm calls and argument handling", recovery: undefined };
    task.plan = [failed, diagnosis];
    expect(() => validateRecoveryReferences([failed], [diagnosis], context)).not.toThrow();
    expect((await reviewPrecondition({ task, step: diagnosis, blockerStep: failed })).allowed).toBe(true);
    expect(resolveTaskProgression(task)).toMatchObject({ kind: "execute-step" });
    expect(failed.status).toBe("failed");
  });

  it("requires a new execution identity even when the replacement fixes the original command", () => {
    const { failed, repair, context } = fixture();
    const replacement = { ...repair, id: failed.id, recovery: undefined,
      command: "cd /opt/report && npm_config_legacy_peer_deps=true bash build.sh" };
    expect(() => validateRecoveryReferences([failed], [replacement], context)).toThrow("PLAN_ATTEMPT_ID_REUSED");
    expect(failed.status).toBe("failed");
    expect(failed.result?.exitCode).toBe(1);
  });

  it.each(["true;", "/usr/bin/true", ": ;", "exit   0;", "command true", "env true", "set -e; /usr/bin/true"])(
    "does not accept a vacuous original validation: %s", validation => {
      const { failed, verify, context } = fixture();
      failed.validation = validation;
      verify.command = validation;
      finish(verify, context);
      expect(hasVerifiedRecovery(failed, verify)).toBe(false);
    },
  );
  it("rejects shared /dev/null and the same build command on project B", () => {
    const { failed, repair, verify } = fixture();
    const unrelated = { ...verify, recovery: undefined, command: "test -d /opt/b/dist >/dev/null" };
    expect(remainingPlanCanRepairPostcondition([unrelated], failed)).toBe(false);
    expect(isRelatedRecoveryStep(failed, { ...repair, command: "cd /opt/b && npm run build", recovery: undefined })).toBe(false);
    expect(isRelatedRecoveryStep(failed, { ...verify, command: unrelated.command })).toBe(false);
    expect(isRelatedRecoveryStep(failed, { ...verify, recovery: { ...verify.recovery!, failedStepId: "failed-b" } })).toBe(false);
    expect(isRelatedRecoveryStep(failed, { ...verify, recovery: { ...verify.recovery!, targetContext: "server-b" } })).toBe(false);
  });

  it("keeps a future recovery visible without using it as a dispatch gate", async () => {
    const { task, failed, repair, next } = fixture();
    task.plan = [failed, next, repair];
    expect(remainingPlanCanRecoverExecutionFailure("network_failure", [next, repair], failed)).toBe(false);
    expect(findUnresolvedBlockingStep(task, next)).toBe(failed);
    const reviewer = vi.fn().mockResolvedValue({ decision: "continue", source: "model" });
    expect((await reviewPrecondition({ task, step: next, blockerStep: failed }, reviewer)).allowed).toBe(true);
    expect(reviewer).not.toHaveBeenCalled();
  });

  it("keeps earlier hard failures as evidence without requiring recovery metadata", async () => {
    const { task, failed, next } = fixture();
    task.executionConstraints = { changePolicy: "requested_changes_only", failurePolicy: "best_effort",
      environmentPolicy: "preserve", prohibitedActions: [], requiredConditions: [], userDirectives: ["try current environment"] };
    const soft = { ...failed, id: "soft", kind: "observe" as const, status: "completed" as const,
      result: { executionStatus: "success" as const, observationStatus: "warning" as const,
        facts: { blockingSignal: true }, warnings: ["risk"], evidenceIds: [] } };
    task.plan = [failed, soft, next];
    const reviewer = vi.fn().mockResolvedValue({ decision: "continue", source: "model" });
    expect((await reviewPrecondition({ task, step: next, blockerStep: soft }, reviewer)).allowed).toBe(true);
    expect(reviewer).not.toHaveBeenCalled();
  });

  it("recovery metadata does not authorize a mutation in a read-only task", async () => {
    const { task, failed, repair, verify } = fixture();
    task.executionConstraints = { changePolicy: "read_only", failurePolicy: "strict",
      environmentPolicy: "preserve", prohibitedActions: [], requiredConditions: [], userDirectives: [] };
    expect((await reviewPrecondition({ task, step: repair, blockerStep: failed })).allowed).toBe(false);
    expect(() => assertTaskPlanAuthorization(task, [repair])).toThrow("只读授权");
    expect(() => assertTaskPlanAuthorization(task, [verify])).not.toThrow();
    expect(() => assertTaskPlanAuthorization(task, [{ ...verify, kind: "change" }])).toThrow("只读授权");
  });

  it("keeps a successful observe detector completed and permits a separately reviewed best_effort attempt", async () => {
    const { task, failed, next } = fixture();
    task.executionConstraints = { changePolicy: "requested_changes_only", failurePolicy: "best_effort",
      environmentPolicy: "preserve", prohibitedActions: [], requiredConditions: [], userDirectives: ["try current environment"] };
    failed.kind = "observe";
    failed.status = "validating";
    failed.result = { executionStatus: "success", observationStatus: "warning", exitCode: 0,
      facts: { blockingSignal: true }, warnings: ["unsupported runtime"], evidenceIds: [] };
    task.plan = [failed, next];
    // Use the real coordination pipeline, beginning with the actual validating
    // state; the reviewer cannot pre-mark the successful detector failed.
    await runEvidenceReviewPipeline({ task, step: failed, reviewRequired: false, postconditionReview: false,
      blockingFacts: failed.result.facts, serverId: task.serverId, taskId: task.id, isCancelled: () => false });
    expect(failed.status).toBe("completed");
    const reviewer = vi.fn().mockResolvedValue({ decision: "continue", source: "model", reason: "authorized attempt", summary: "risk remains" });
    expect((await reviewPrecondition({ task, step: next, blockerStep: failed }, reviewer)).allowed).toBe(true);
    expect(failed.result.facts.blockingSignal).toBe(true);
  });

  it("retains an archived failure and only matches its historical proof after actual verification", async () => {
    const { task, failed, repair, verify, next, context } = fixture();
    task.phaseHistory = [{ id: "previous", roundId: "round", requirement: task.title, reason: "adjustment",
      plan: [failed], createdAt: "now", completedAt: "now" }];
    task.plan = [repair, verify, next];
    expect((await reviewPrecondition({ task, step: repair, blockerStep: failed })).allowed).toBe(true);
    finish(repair, context);
    expect(findUnresolvedBlockingStep(task, next)).toBe(failed);
    expect((await reviewPrecondition({ task, step: verify, blockerStep: failed })).allowed).toBe(true);
    verify.review = { decision: "complete", reason: "model says done", summary: "done", source: "model" };
    expect(hasVerifiedRecovery(failed, verify)).toBe(false);
    finish(verify, context);
    expect(findUnresolvedBlockingStep(task, next)).toBeUndefined();
    expect(recoveryPlanningContext(task).failedAttempts.map(attempt => attempt.failedStepId)).toEqual([failed.id]);
    expect(failed.status).toBe("failed");
    verify.result!.exitCode = 1;
    expect(findUnresolvedBlockingStep(task, next)).toBe(failed);
  });

  it("hands a recovery-only stage to goal review while retaining unresolved evidence", () => {
    const { task, failed, repair, verify, context } = fixture();
    finish(repair, context);
    task.plan = [failed, repair];
    expect(resolveTaskProgression(task).kind).toBe("complete");
    expect(recoveryPlanningContext(task).failedAttempts.map(attempt => attempt.failedStepId)).toEqual([failed.id]);
    finish(verify, "different-target");
    expect(hasVerifiedRecovery(failed, verify)).toBe(false);
    finish(verify, context);
    verify.evidence = [];
    expect(hasVerifiedRecovery(failed, verify)).toBe(false);
  });

  it("tracks verification identity without turning target mismatch into dispatch denial", async () => {
    const { task, failed, verify } = fixture();
    task.agentSessionId = "reconnected";
    task.agentSessionGeneration = 3;
    task.credentialRevision = 2;
    expect((await reviewPrecondition({ task, step: verify, blockerStep: failed })).allowed).toBe(true);
    finish(verify, taskAttemptContext(task));
    expect(hasVerifiedRecovery(failed, verify)).toBe(true);
    task.executionTargetServerId = "other-server";
    expect(isRelatedRecoveryStep(failed, verify, taskAttemptContext(task))).toBe(false);
    expect((await reviewPrecondition({ task, step: verify, blockerStep: failed })).allowed).toBe(true);
    task.executionTargetServerId = task.serverId;
    task.currentRoundId = "other-round";
    expect(isRelatedRecoveryStep(failed, verify, taskAttemptContext(task))).toBe(false);
    expect((await reviewPrecondition({ task, step: verify, blockerStep: failed })).allowed).toBe(true);
  });

  it("keeps a required original-contract verification despite previous identical observations", () => {
    const { failed, verify, context } = fixture();
    const prior = { ...verify, id: "earlier-observation", recovery: undefined };
    finish(prior, context);
    const history = [failed, prior];
    expect(selectAdjustmentSteps(history, [verify], context)).toEqual([verify]);
    expect(selectContinuationSteps(history, [verify], context)).toEqual([verify]);
    const invalid = { ...verify, recovery: { ...verify.recovery!, failedStepId: "different-failure" } };
    expect(selectAdjustmentSteps(history, [invalid], context)).toEqual([invalid]);
    expect(() => validateRecoveryReferences(history, [invalid], context)).not.toThrow();
    expect(isRelatedRecoveryStep(failed, invalid, context)).toBe(false);
  });

  it("rechecks an observe blocker using its original observation contract", () => {
    const { failed, verify, context } = fixture();
    failed.kind = "observe";
    failed.validation = "";
    failed.command = 'test "$(custom-runtime-check --project /opt/a)" = supported';
    failed.result!.facts.blockingSignal = true;
    verify.command = failed.command;
    finish(verify, context);
    verify.result!.facts.blockingSignal = true;
    expect(hasVerifiedRecovery(failed, verify)).toBe(false);
    verify.result!.facts.blockingSignal = false;
    expect(hasVerifiedRecovery(failed, verify)).toBe(true);
  });

  it("preserves failed evidence while accepting the model's completion branch", () => {
    const { failed, repair, verify } = fixture();
    failed.status = "validating";
    failed.result!.executionStatus = "success";
    failed.result!.facts.validationPassed = false;
    expect(applyExecutionEvidenceReview({ step: failed, remainingSteps: [repair, verify],
      review: { decision: "continue", source: "model", reason: "recover", summary: "recover" },
      reviewWasRequired: true }).shouldAdvance).toBe(true);
    expect(failed.status).toBe("failed");
    repair.status = "validating";
    applyExecutionEvidenceReview({ step: repair, remainingSteps: [verify], reviewWasRequired: true,
      review: { decision: "complete", source: "model", reason: "done", summary: "done" } });
    expect(verify.status).toBe("skipped");
    expect(failed.status).toBe("failed");
    expect(failed.result?.facts.validationPassed).toBe(false);
  });

  it("preserves protocol metadata and rejects malformed or self-referential recovery", () => {
    const { repair, verify } = fixture();
    expect(normalizePlanPreconditions([verify])[0].recovery).toEqual(verify.recovery);
    expect(() => normalizePlanPreconditions([{ ...repair, recovery: { ...repair.recovery!, failedStepId: repair.id } }])).toThrow("recovery");
    expect(() => normalizePlanPreconditions([{ ...verify, recovery: { ...verify.recovery!, purpose: "repair" } }])).toThrow("RECOVERY_KIND_MISMATCH");
  });

  it("retains a persisted failure audit reference after detailed phases are trimmed", () => {
    const { task, failed, repair, verify, next, context } = fixture();
    task.plan = [repair, verify, next];
    task.phaseHistory = [];
    task.historyCheckpoint = { version: 2, sourceRoundCount: 1, sourcePhaseCount: 1, sourceStepCount: 1,
      statusCounts: { failed: 1 }, verifiedFacts: [], phaseSummaries: [], updatedAt: "now", sourceHistoryFingerprint: "persisted",
      unresolvedIssues: [{ stepId: failed.id, title: failed.title, status: "failed", commandFingerprint: "a",
        attemptCount: 1, attemptContext: context, sourceRoundId: "round", blocksExecution: true,
        recoveryContract: persistedRecoveryContract(failed, "round") }] };
    expect(findUnresolvedBlockingStep(task, next)?.id).toBe(failed.id);
    finish(verify, context);
    expect(findUnresolvedBlockingStep(task, next)).toBeUndefined();
    task.historyCheckpoint!.unresolvedIssues[0].recoveryContract = undefined;
    expect(findUnresolvedBlockingStep(task, next)?.result?.facts.recoveryContractMissing).toBe(true);
    const planning = recoveryPlanningContext(task);
    expect(planning.failedAttempts[0].verificationContractMissing).toBe(true);
    expect(planning.failedAttempts[0].verification.acceptanceInstruction).toContain("可继续只读诊断");
    expect(() => validateRecoveryReferences([failed], [next], context)).not.toThrow();
    task.currentRoundId = "new-user-goal";
    expect(findUnresolvedBlockingStep(task, next)?.result?.facts.recoveryContractMissing).toBe(true);
  });
});
