import type { PlanStep } from "@/types";

const STARTUP_FILE = /(?:^|[\s'"/])(?:\.bashrc|\.bash_profile|\.bash_login|\.profile|\.zshrc)(?:[\s'";]|$)/;
const STARTUP_MUTATION = /(?:sed\s+-i|tee\s|cat\s*>|printf[\s\S]*>|cp\s|mv\s|truncate\s)/i;
const STARTUP_TARGET = /(?:~|\$HOME|\$\{HOME\}|\/[^\s'"`;|&<>()]+)\/\.(?:bashrc|bash_profile|bash_login|profile|zshrc)/g;

export interface ShellStartupTransaction {
  targets: string[];
  backupPaths: string[];
  snapshotCommand: string;
  rollbackCommand: string;
}

export function isShellStartupMutation(step: Pick<PlanStep, "command">) {
  return STARTUP_FILE.test(step.command) && STARTUP_MUTATION.test(step.command);
}

export function shellStartupValidationScope(
  step: Pick<PlanStep, "command">,
): "fresh_interactive_shell" | "fresh_login_shell" | undefined {
  if (!isShellStartupMutation(step)) return undefined;
  return /\.bash_profile|\.bash_login|\.profile/.test(step.command)
    ? "fresh_login_shell"
    : "fresh_interactive_shell";
}

export function validateShellStartupTransaction(step: PlanStep) {
  if (!isShellStartupMutation(step)) return;
  const requiredScope = shellStartupValidationScope(step)!;
  if (step.validationScope !== requiredScope) {
    throw new Error(`Shell 启动文件变更必须使用 ${requiredScope} 独立验收`);
  }
  if (!/\bmktemp\b/.test(step.command) || !/\bmv\b/.test(step.command)) {
    throw new Error("Shell 启动文件变更必须使用 mktemp 和 mv 原子提交");
  }
  if (!(step.command.match(STARTUP_TARGET) ?? []).length) {
    throw new Error("Shell 启动文件变更必须使用明确的 HOME 或绝对目标路径");
  }
  if (/(?:^|[;\n]\s*)(?:source|\.)\s+[^;\n]+/m.test(step.validation)) {
    throw new Error("Shell 启动文件验收不得显式 source 目标文件");
  }
}

function shellSingleQuote(value: string) {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

function targetAssignment(target: string) {
  const homeRelative = target.match(/^(?:~|\$HOME|\$\{HOME\})(\/.*)$/);
  return homeRelative ? `"$HOME${homeRelative[1]}"` : shellSingleQuote(target);
}

/**
 * Builds an executor-owned snapshot/rollback pair. The model only describes the
 * intended atomic mutation; recovery metadata is generated by the trusted
 * execution layer and never depends on parsing a model-provided backup name.
 */
export function buildShellStartupTransaction(
  step: Pick<PlanStep, "command">,
  transactionId: string,
): ShellStartupTransaction | undefined {
  if (!isShellStartupMutation(step)) return undefined;
  const targets = [...new Set(step.command.match(STARTUP_TARGET) ?? [])];
  if (!targets.length) {
    throw new Error("Shell 启动文件变更无法确定需要快照的目标路径");
  }
  const safeId = transactionId.replace(/[^A-Za-z0-9_-]/g, "-");
  const backupPaths = targets.map((target) => `${target}.opsark-agent-${safeId}.bak`);
  const snapshot = ["set -eu"];
  const rollback = ["set -eu"];
  targets.forEach((target, index) => {
    const suffix = index + 1;
    const targetVar = `opsark_target_${suffix}`;
    const backupVar = `opsark_backup_${suffix}`;
    const absentVar = `opsark_absent_${suffix}`;
    const restoreVar = `opsark_restore_${suffix}`;
    snapshot.push(
      `${targetVar}=${targetAssignment(target)}`,
      `${backupVar}="\${${targetVar}}.opsark-agent-${safeId}.bak"`,
      `${absentVar}="\${${backupVar}}.absent"`,
      `if test -e "\${${targetVar}}"; then`,
      `  cp -p -- "\${${targetVar}}" "\${${backupVar}}"`,
      "else",
      `  : > "\${${absentVar}}"`,
      "fi",
      `printf 'OPSARK_STARTUP_SNAPSHOT=%s\\n' "\${${backupVar}}"`,
    );
    rollback.push(
      `${targetVar}=${targetAssignment(target)}`,
      `${backupVar}="\${${targetVar}}.opsark-agent-${safeId}.bak"`,
      `${absentVar}="\${${backupVar}}.absent"`,
      `if test -e "\${${backupVar}}"; then`,
      `  ${restoreVar}=$(mktemp "\${${targetVar}}.opsark-restore.XXXXXX")`,
      `  cp -p -- "\${${backupVar}}" "\${${restoreVar}}"`,
      `  mv -f -- "\${${restoreVar}}" "\${${targetVar}}"`,
      `elif test -e "\${${absentVar}}"; then`,
      `  rm -f -- "\${${targetVar}}"`,
      "else",
      `  printf 'missing startup snapshot: %s\\n' "\${${backupVar}}" >&2`,
      "  exit 1",
      "fi",
      `printf 'OPSARK_STARTUP_ROLLBACK=%s\\n' "\${${targetVar}}"`,
    );
  });
  return {
    targets,
    backupPaths,
    snapshotCommand: snapshot.join("\n"),
    rollbackCommand: rollback.join("\n"),
  };
}

export function shellStartupPrecedenceDiscoveryCommand(home = "$HOME") {
  return [
    "set -e",
    `for f in ${home}/.bash_profile ${home}/.bash_login ${home}/.profile ${home}/.bashrc; do`,
    "  if test -e \"$f\"; then printf '%s\\n' \"$f\"; fi",
    "done",
  ].join("\n");
}
